version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: fluxpay-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fluxpay
      POSTGRES_USER: fluxpay
      POSTGRES_PASSWORD: fluxpay
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
